#!/usr/bin/env python
import os
import sys

from methods import print_error


libname = "godot-dojo"
projectdir = "project"

localEnv = Environment(tools=["default"], PLATFORM="")

# Build profiles can be used to decrease compile times.
# You can either specify "disabled_classes", OR
# explicitly specify "enabled_classes" which disables all other classes.
# Modify the example file as needed and uncomment the line below or
# manually specify the build_profile parameter when running SCons.

# localEnv["build_profile"] = "build_profile.json"

customs = ["custom.py"]
customs = [os.path.abspath(path) for path in customs]

opts = Variables(customs, ARGUMENTS)
opts.Update(localEnv)

Help(opts.GenerateHelpText(localEnv))

env = localEnv.Clone()

if not (os.path.isdir("external/godot-cpp") and os.listdir("external/godot-cpp")):
    print_error("""godot-cpp is not available within this folder, as Git submodules haven't been initialized.
Run the following command to download godot-cpp:

    git submodule update --init --recursive""")
    sys.exit(1)

env = SConscript("external/godot-cpp/SConstruct", {"env": env, "customs": customs})

targets = {
    ("windows", "x86_64"): "x86_64-pc-windows-gnu",
    ("linux", "x86_64"): "x86_64-unknown-linux-gnu",
    ("linux", "arm64"): "aarch64-unknown-linux-gnu",
    ("macos", "x86_64"): "x86_64-apple-darwin",
    ("macos", "arm64"): "aarch64-apple-darwin",
    ("macos", "universal"): ["x86_64-apple-darwin", "aarch64-apple-darwin"],
    ("web", "wasm32"): "wasm32-unknown-emscripten",
    ("android", "arm64"): "aarch64-linux-android",
    ("ios", "arm64"): "aarch64-apple-ios" if not env['ios_simulator'] else "aarch64-apple-ios-sim",
    ("ios", "x86_64"): "x86_64-apple-ios",
    ("ios", "universal"): ["aarch64-apple-ios", "x86_64-apple-ios", "aarch64-apple-ios-sim"],
}

rust_lib_path = f"godot-dojo-core/target/x86_64-unknown-linux-gnu/debug/libgodot_dojo_core.a"
rust_web_lib_path = f"godot-dojo-core/target/wasm32-unknown-emscripten/debug/libgodot_dojo_core.a"
# rust_web_lib_path = f"godot-dojo-core/target/wasm32-unknown-unknown/debug/libgodot_dojo_core.a"

print(rust_lib_path)

if env["platform"] == "web":
    env.Append(LIBS=[File(rust_web_lib_path)])
    env.Append(LINKFLAGS=["-Wl,--fatal-warnings", "-sASSERTIONS=1", "-g", "-gsource-map", "-semit-symbol-map", "-sEMULATE_FUNCTION_POINTER_CASTS=1"])
else:
    env.Append(LIBS=[File(rust_lib_path)])
env.Append(CPPPATH=["src/", "include/", "bindings/", "external/boost/include"])
sources = []
for root, dirs, files in os.walk("src"):
    for file in files:
        if file.endswith(".cpp"):
            sources.append(os.path.join(root, file))
sources.extend(["bindings/controller/controller.cpp", "bindings/dojo/dojo.cpp"])


if env["target"] in ["editor", "template_debug"]:
    try:
        doc_data = env.GodotCPPDocData("src/gen/doc_data.gen.cpp", source=Glob("doc_classes/*.xml"))
        sources.append(doc_data)
    except AttributeError:
        print("Not including class reference as we're targeting a pre-4.3 baseline.")

# .dev doesn't inhibit compatibility, so we don't need to key it.
# .universal just means "compatible with all relevant arches" so we don't need to key it.
suffix = env['suffix'].replace(".dev", "").replace(".universal", "")

lib_filename = "{}{}{}{}".format(env.subst('$SHLIBPREFIX'), libname, suffix, env.subst('$SHLIBSUFFIX'))

library = env.SharedLibrary(
    "bin/{}/{}".format(env['platform'], lib_filename),
    source=sources,
)

copy = env.Install("{}/bin/{}/".format(projectdir, env["platform"]), library)

default_args = [library, copy]
Default(*default_args)
