import os

from methods import _detect_godot_min_requirement, get_git_version

def exists(env):
    return True

def generate(env):
    env.Append(CPPPATH=["src/", "include/", "external/boost/include"])
    if env["platform"] != "web":
        env.Append(CPPPATH=["bindings/"])

    with open("plugin_template.gdextension.in", 'r') as f:
        template = f.read()

    godot_min = _detect_godot_min_requirement()
    project_version = get_git_version()
    precision = ""
    libname = env["libname"]
    projectdir = env["projectdir"]

    if env["precision"] == "double":
        precision = ".double"

    gdext = template.replace("${PROJECT_NAME}", libname)
    gdext = gdext.replace("${ENTRY_POINT}", "godotdojo_library_init")

    gdext = gdext.replace("${GODOT_MIN_REQUIREMENT}", godot_min)
    gdext = gdext.replace("${VERSION}", project_version)

    gdext = gdext.replace("${PRECISION}", precision)

    with open(f"{projectdir}/godot-dojo.gdextension", 'w') as f:
        f.write(gdext)

    version_header_path = "include/gen/version.gen.hpp"
    version_header_content = f"""/* THIS FILE IS GENERATED BY SCONS. DO NOT EDIT. */
    #ifndef GODOT_DOJO_VERSION_GEN_HPP
    #define GODOT_DOJO_VERSION_GEN_HPP
    #define GODOT_DOJO_VERSION "{project_version}"
    #define GODOT_DOJO_PRECISION "{precision}"
    #endif // GODOT_DOJO_VERSION_GEN_HPP
    """

    os.makedirs(os.path.dirname(version_header_path), exist_ok=True)
    if not os.path.exists(version_header_path) or open(version_header_path, "r").read() != version_header_content:
        with open(version_header_path, "w") as f:
            f.write(version_header_content)